### ISSUE TITLE
ubuntu 20.04 dropped support for tls versions used by osu!stable

### ISSUE THREAD

**Issue by ledlamp** [cmyui/gulag#107]
> - ubuntu 20.04 & nginx have unknown issues? i recommend using 18.04

apparently osu uses older tls 1.2 or 1.1 which ubuntu 20.04 doesn't support but 18.04 does.

I tried adding 
```
ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH:@SECLEVEL=1";
```
~~to nginx config but it didn't work.~~ edit: not sure where I tried it (i think on centos 8) but it worked on 20.04

So if you can somehow enable TLS 1.0/1.1 then it should work.

Alternatively you could just use cloudflare, which supports it.

**Comment by cmyui** [comment]
Ooh interesting, I wasn't aware 20.04 dropped support for older versions.. I'll do some further research and update the readme accordingly to advise people, thanks!
