### ISSUE TITLE
Running gulang with pypy3

### ISSUE THREAD

**Issue by m0lese** [cmyui/gulag#117]
Is gulag hardly dependent on python3.9? Does it work on python3.7?

I was wondering weather gulag would run with [pypy](https://www.pypy.org)!

**Comment by alowave223** [comment]
Yeah, here is many features that available only from 3.9+ version of python

**Comment by m0lese** [comment]
@alowave223 Can you mention those features?

**Comment by alowave223** [comment]
The list will be huge, trust me, the gulag developer is actively using the new features that the language gives him, constantly learning and finding even more uses for the new features.

**Comment by alowave223** [comment]
I think there is no way to backport gulag to older versions

**Comment by m0lese** [comment]
Gotcha!
