### ISSUE TITLE
Download default avatar if not found (causes confusing FileNotFoundError out of the box)

### ISSUE THREAD

**Issue by ledlamp** [cmyui/gulag#137]
looks like gulag automatically downloads flag images on the first run but not the default avatar so it just spams unhandled filenotfounderrors out of the box

**Comment by cmyui** [comment]
closed in dd63c7d

**Comment by ledlamp** [comment]
![:sGrimace:](https://cdn.discordapp.com/emojis/707719977490317362.png?size=48)
![image](https://user-images.githubusercontent.com/24686877/142740970-9a45c442-b125-4b94-b99f-2038452200b1.png)
