### ISSUE TITLE
Write syntax error

### ISSUE THREAD

**Issue by smpial** [cmyui/gulag#148]
When I launch code, i get syntax error
`  File "main.py", line 126
    misc.context.acquire_http_session(glob.has_internet) as glob.http_session,
                                                         ^
SyntaxError: invalid syntax`

**Comment by JKBGL** [comment]
> When I launch code, i get syntax error ` File "main.py", line 126 misc.context.acquire_http_session(glob.has_internet) as glob.http_session, ^ SyntaxError: invalid syntax`
Are you on main or fastapi?

**Comment by smpial** [comment]
> > When I launch code, i get syntax error ` File "main.py", line 126 misc.context.acquire_http_session(glob.has_internet) as glob.http_session, ^ SyntaxError: invalid syntax`
> 
> Are you on main or fastapi?

main i think

**Comment by smpial** [comment]
> When I launch code, i get syntax error ` File "main.py", line 126 misc.context.acquire_http_session(glob.has_internet) as glob.http_session, ^ SyntaxError: invalid syntax`

error on "as" word

**Comment by smpial** [comment]
I fixel it using python 3.10 instead of python 3.9
