### ISSUE TITLE
(PYL-R1706) Consider using if expression

### ISSUE THREAD

**Issue by Uniminin** [cmyui/gulag#21]
## Description
At line [handlers.py#L229](https://github.com/cmyui/gulag/blob/master/handlers.py#L229), One of known pre Python 2.5 ternary syntax is being used. It is recommended to use an if expression like: `X if condition else Y`. Using `[condition] and [on_true] or [on_false]` may also give wrong results when `on_true` has a false boolean value. *The inconsistency:* Consider the following: 
```python
path = _path if os.path.exists(_path) else default_avatar
```

## Occurrences
There is just only 1 occurrence of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/Uniminin/gulag/issue/PYL-R1706/occurrences/](https://deepsource.io/gh/Uniminin/gulag/issue/PYL-R1706/occurrences/)

**Comment by cmyui** [comment]
naw this was written intentionally, i'm well aware of how it works :D
