### ISSUE TITLE
(PYL-R1705) Unnecessary `else` / `elif` used after `return`

### ISSUE THREAD

**Issue by Uniminin** [cmyui/gulag#23]
## Description
`return` statement causes the control flow to be disrupted, making the `else` / `elif` block here unnecessary. This doesn&#x27;t mean you can not use it, but it is recommended to refactor this for a better readability. Bad:
```python 
def classify_number(x): if x % 2 == 0: return "Even" else: return …
```

## Occurrences
There are 9 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/Uniminin/gulag/issue/PYL-R1705/occurrences/](https://deepsource.io/gh/Uniminin/gulag/issue/PYL-R1705/occurrences/)

**Comment by cmyui** [comment]
I agree using elif after a return usually looks pretty confusing, i think the else cases are mostly fine.. very low concern though honestly, these are all pretty readable already already
