### ISSUE TITLE
(PYL-W0703) Very General Exception caught

### ISSUE THREAD

**Issue by Uniminin** [cmyui/gulag#24]
- Affected Line: [commands.py#L365](https://github.com/cmyui/gulag/blob/master/constants/commands.py#L365)

## Description
If the except block catches a very general exception, it is likely to include many unrelated errors too. Try to be more precise while catching the exception.

## Occurrences
There is 1 occurrence of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/Uniminin/gulag/issue/PYL-W0703/occurrences/](https://deepsource.io/gh/Uniminin/gulag/issue/PYL-W0703/occurrences/)

**Comment by cmyui** [comment]
this is on purpose (pretty easy to tell why with the context, eval can throw a lot of different errors)
