### ISSUE TITLE
(PYL-W0143) Comparison with callable detected

### ISSUE THREAD

**Issue by Uniminin** [cmyui/gulag#26]
## Description
Comparison with a callable has been detected, which suggests you may have forgotten the parentheses to actually call the function or method. If you intended to check if both of these callables are the same, it&#x27;s recommended to use the `is` operator for comparison.

## Occurrences
There are 4 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/Uniminin/gulag/issue/PYL-W0143/occurrences/](https://deepsource.io/gh/Uniminin/gulag/issue/PYL-W0143/occurrences/)

**Comment by cmyui** [comment]
not sure what this is on about? i'm checking intenum internal values against ints, this is perfectly valid & working.
