### ISSUE TITLE
No sort of update log for sql and configuration changes.

### ISSUE THREAD

**Issue by cmyui** [cmyui/gulag#30]
When I first started designing, I didn't think I'd be making such frequent changes to the structure of the database; turns out this happens much more than I was anticipating, and leaving it on users to make their own queries to fix their sql isn't great..

Will probably just make a log file with copy-pastable updates for each version release with sql changes

**Comment by Yo-ru** [comment]
You could have an update.py file that runs when the sever notices the version changes. It can make sql changes and whatever else needs to be done to dependencies before accepting client connections.

**Comment by cmyui** [comment]
Resolved in v3.0.4; forgot to close the issue haha.
