### ISSUE TITLE
Multiplayer

### ISSUE THREAD

**Issue by barrack-obama** [cmyui/gulag#38]
Multiplayer chat is still listed in channels after leaving a multiplayer lobby

![image](https://user-images.githubusercontent.com/45692977/99906162-d352b080-2cd5-11eb-95f1-b757e1910e0b.png)
![image](https://user-images.githubusercontent.com/45692977/99906169-dbaaeb80-2cd5-11eb-8230-8e8951f1baa6.png)

**Comment by barrack-obama** [comment]
And when you try to join it:

![image](https://user-images.githubusercontent.com/45692977/99906323-c84c5000-2cd6-11eb-924d-df995f75bcd4.png)

**Comment by cmyui** [comment]
Thanks for posting the issue :)
