### ISSUE TITLE
cant login

### ISSUE THREAD

**Issue by lokillo999** [cmyui/gulag#42]
once installed from scratch gulag if it allows me to register but when trying to login i get this error
![image](https://user-images.githubusercontent.com/19214569/102735796-8e379380-4300-11eb-9de1-ceb033d5ab54.png)
and when seeing the mysql tables if my user appears
![image](https://user-images.githubusercontent.com/19214569/102735944-e79fc280-4300-11eb-9812-7eccec53bf32.png)

**Comment by cmyui** [comment]
Resolved in [Discord](https://discord.com/invite/ShEQgUx).
