### ISSUE TITLE
Add IRC Functionality

### ISSUE THREAD

**Issue by memsdm05** [cmyui/gulag#52]
## Summary
The offical osu! server has an IRC server. So does Ripple. They provide a platform for external bots such as [Tillerino ](https://github.com/Tillerino/Tillerinobot) and [MaidBot ](https://osu.ppy.sh/users/16173747) to operate, enriching the user experience on their respective server. I propose we do the same, although make it async.

## Motivation
A lot of a private server's job is to emulate Bancho while also adding new features. Even though IRC is not essential to a Bancho clone, it however allows bots to run without needing a Bancho connection. Mostly, this serves as compatibility, since most osu bot frameworks work via IRC (i.e. [bancho.js](https://bancho.js.org/)). Also, it's cool.

## Describe alternatives you've considered
Using a "modern" IRC-like service (like Firebase) would render the compatibility aspect useless. The only purpose IRC serves on osu! is interacting with osu's chat. It can't submit scores, or even lookup user data. Simple is good.

## Additional context
I'm willing to develop it as @cmyui already has enough on his plate. _Think of it as an initiation project_. If it never gets delivered, it won't cripple Gulag's infrastructure. Likewise, if it does get delivered it (should) warrant a version increase (@cmyui can i commit to devel?)

**Some objectives for the IRC server**
- [ ]  Seamless integration into existing code (Bancho user == IRC user)
- [ ]  irc.ppy.sh compatible
- [ ]  Redirects DMs to BanchoBot to Aiko
- [ ]  Token protected
- [ ]  DB table for storing IRC usernames and tokens (with a relational element to userids)
- [ ]  gulag-web interface for creating tokens (talk with @Yo-ru about that one)
- [ ]  command for creating tokens
- [ ]  async (runs in main loop instead of threads, because screw threads)
- [ ]  lightweight and fast (ad hoc, not a thin layer over a dependency) 
- [ ]  works with IRC clients like HexChat

-- sansquick

**Comment by cmyui** [comment]
going to close this for the time being, as it's not being actively pursued anymore.

if no one gets around to this before me, i will likely work on it when the server is in a more complete state (at least a few months).
