### ISSUE TITLE
Guide/Utility for Generating SSL Certs for -devserver 

### ISSUE THREAD

**Issue by memsdm05** [cmyui/gulag#63]
Since its not legally murky, it will prevent plenty of headaches.

edit: mainly for localhost applications since the same objective can be achieved with Cloudflare and/or LetsEncrypt.

**Comment by memsdm05** [comment]
[Done](https://github.com/cmyui/gulag/commit/d27bf6719de18e0c08191dd5ffa603d914f2e878)

**Comment by memsdm05** [comment]
![image](https://user-images.githubusercontent.com/32436024/110995919-1f8b3480-8349-11eb-8800-dae5088cd504.png)

**Comment by cmyui** [comment]
LOL
