### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by memsdm05** [cmyui/gulag#65]
gulag-web has one how come we don't. hmph

**Comment by Atakku** [comment]
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_the_Soviet_Union.svg/1280px-Flag_of_the_Soviet_Union.svg.png"/>
i beg to differ

**Comment by cmyui** [comment]
if someone proposes a logo sure but i'm far from a designer myself lol..
also personally could care less for anything so only if it's really clean probably :P

**Comment by Varkaria** [comment]
hi
