### ISSUE TITLE
Api last seen

### ISSUE THREAD

**Issue by def750** [cmyui/gulag#84]
I recommend adding last seen timestamp to output of /api/get_player_status?id={id} when user is offline

**Comment by cmyui** [comment]
The `latest_activity` column in the users table could be used for this.

**Comment by def750** [comment]
> The `latest_activity` column in the users table could be used for this.

Yeah but still this option would be nice via api, I don't think it's much to implement because its just taking data from one column as you said.

**Comment by tsunyoku** [comment]
That’s cmyui’s point - he’s giving you a pointer on to how to implement it yourself.

**Comment by def750** [comment]
> That’s cmyui’s point - he’s giving you a pointer on to how to implement it yourself.

Oke, I'll do it myself.
